### ISSUE TITLE
No reponse from Wifi Stick

### ISSUE THREAD

**Issue by Uwe-Kaki** [Kotty666/dbus-growatt-shinex#13]
Hello,
I have successfully installed the service, it is up and running : but showing only the voltage of L1 / AC Phase L1

The Wifi Stick IP adress is responding on "ping" from putty ( retrieved from my fritzbox )

The logs show : 2023-06-21 15:17:38,135 root INFO No response from Shine X - http://growatt-600.fritz.box/status

I tried with my "normal" Growatt username / password or without, various qoutes, nothing worked.

do you have any idea what else I could check ?

How could I stop the service in the meantime or uninstall the project for the time being ?
![Remote Console](https://github.com/Kotty666/dbus-growatt-shinex/assets/75257707/95e5c1bd-7935-4e17-8d80-e39c9b47db3c)

Or do I have have a complete missunderstanding of the project ?

PS : response in German would be ok as well.

Many

**Comment by Je68le** [comment]
Hi Uwe-Kai,

had the same missunderstanding as you at first. The service only works with a special prepared USB stick (take a look to [https://github.com/Alkhateb/Growatt_ShineWiFi-X](https://github.com/Alkhateb/Growatt_ShineWiFi-X) how to prepare it). In my case I ordered an extra Shine-X WiFi adapter to flash the firmware (only to minimize the risk of any issue) and then it works as expected.

Hope that helps
