### ISSUE TITLE
Growatt ShineLan-X Adapter

### ISSUE THREAD

**Issue by buddhafragt** [Kotty666/dbus-growatt-shinex#17]
Hallo,
den WIFI Stick bekomme ich nicht zu laufen, läuft das Script auch mit einem Growatt ShineLan-X Adapter?
Ist das Script mit einer Venus Firmware 3.4 (oder >3.0) getestet?

**Comment by Kotty666** [comment]
Hi,
also mit VenusOS >3 funktioniert das script
Wegen dem ShineLan-X: 
Wenn du die Firmware von https://github.com/OpenInverterGateway/OpenInverterGateway auf den drauf bekommst dann funktioniert es.
