### ISSUE TITLE
How to find IP of ShineX-Wifi

### ISSUE THREAD

**Issue by Brekkis** [Kotty666/dbus-growatt-shinex#3]
I searched in the App, did a Networksscan with different Apps, search in the Fritz....
But i cannot find the IP. 🤷🏼‍♂️

Fan you give me a hint. 

Regards Stefan

**Comment by Kotty666** [comment]
@Brekkis did you flash your Stick with this Firmware?
https://github.com/otti/Growatt_ShineWiFi-S

**Comment by Brekkis** [comment]
No, Stick is running on original Firmware!
I cant find out the IP of the Stick!

**Comment by Kotty666** [comment]
@Brekkis this script only works with the Firmware from Otti and after flashing this, you'll find the IP in your network.
