### ISSUE TITLE
2. Wechselrichter hinzufügen

### ISSUE THREAD

**Issue by Sven4597** [Kotty666/dbus-growatt-shinex#6]
Hallo, ist es möglich auch einen zweiten Wechselrichter hinzufügen?

Ich habe es versucht mit einem anderen Namen und ID aber dann wird wohl der alte Eintrag überschrieben.

**Comment by Sven4597** [comment]
@Kotty666 
Ich habe es hinbekommen mehre Wechselrichter zu integrieren. 

Weitere Wechselrichter anlegen:
Verzeichniss kopieren
root@raspberrypi2:~# 		cp -r /data/dbus-growatt-shinex /data/dbus-growatt-shinex2
2. Wechselrichter installieren
root@raspberrypi2:~# 		/data/dbus-growatt-shinex2/install.sh
Config für 2. Wechselrichter bearbeiten
root@raspberrypi2:~# 		nano /data/dbus-growatt-shinex2/config.ini
F2 zum speichern
Y bestätigen
Reboot

Was leider nicht geht wenn ich bei dem 2. Wechselrichter L2 angebe. Es werden jetzt alle Wechselrichter auf L1 addiert.

**Comment by Nicolas76x** [comment]
Hi, 

Is the problem in the sending to DBus part where it all gets L1?

Thx
Nicolas

**Comment by kufo78** [comment]
> @Kotty666 Ich habe es hinbekommen mehre Wechselrichter zu integrieren.
> 
> Weitere Wechselrichter anlegen: Verzeichniss kopieren root@raspberrypi2:~# cp -r /data/dbus-growatt-shinex /data/dbus-growatt-shinex2 2. Wechselrichter installieren root@raspberrypi2:~# /data/dbus-growatt-shinex2/install.sh Config für 2. Wechselrichter bearbeiten root@raspberrypi2:~# nano /data/dbus-growatt-shinex2/config.ini F2 zum speichern Y bestätigen Reboot
> 
> Was leider nicht geht wenn ich bei dem 2. Wechselrichter L2 angebe. Es werden jetzt alle Wechselrichter auf L1 addiert.

Muss man kopieren oder warum hast du den Text durchgestrichen ?

**Comment by Sven4597** [comment]
keine Ahnung warum das Durchgestrichen ist sollte nicht sein.

**Comment by Kotty666** [comment]
@Sven4597 @kufo78 

ja das mit dem Kopieren geht - leider habe ich keinen Growatt mehr hier.
Das Problem der Phase ist, dass der growatt immer erzählt er wäre an L1

Ich denke ich habe da eine Idee da baue ich gleich mal eine Testversion wäre es für euch möglich das zu testen?

**Comment by Sven4597** [comment]
Ja kann ich gerne mal testen.

**Comment by Kotty666** [comment]
@Sven4597 code ist hier zu finden https://github.com/Kotty666/dbus-growatt-shinex/tree/issue6

**Comment by Sven4597** [comment]
> @Sven4597 code ist hier zu finden https://github.com/Kotty666/dbus-growatt-shinex/tree/issue6

Hallo,
konnte es heute mal testen doch leider wir er immer noch auf L1 angezeigt. Hatte L3 angegeben.

![Victron2](https://github.com/Kotty666/dbus-growatt-shinex/assets/47686540/0a8c74e2-4492-40f2-a607-95770588a2b5)

**Comment by Kotty666** [comment]
Fix Merged

**Comment by Kotty666** [comment]
Fix Merged

**Comment by Sven4597** [comment]
> Zusammengeführte Korrektur

Hallo, hast du nochmals was geändert?

**Comment by Kotty666** [comment]
> > Zusammengeführte Korrektur
> 
> Hallo, hast du nochmals was geändert?

Ja, ich habe an dem Thema in 2 Branches gearbeitet und das nun mal zusammen nach main gebracht.

Am besten alles auscheck da ich das logverhalten auch umgebaut habe und dann die install.sh ausführen (Logging nun über den internen VenusOS Logger)

**Comment by Sven4597** [comment]
Jetzt geht es.

![image](https://github.com/Kotty666/dbus-growatt-shinex/assets/47686540/188cfceb-c20c-45f8-b643-88ffb91a7aa8)

Super vielen Dank

**Comment by Sven4597** [comment]
> > > Zusammengeführte Korrektur
> > 
> > 
> > Hallo, hast du es nochmal geändert?
> 
> Ja, ich habe an dem Thema in 2 Branchen gearbeitet und das nun mal zusammen zum Erfolg gebracht.
> 
> Am besten alles auschecken da ich das Logverhalten auch umgebaut habe und dann die install.sh ausführen (Logging nun über den internen VenusOS Logger)

Wie kann ich das am besten auschecken?
Habe es auf meinem Test Pi versucht

**Comment by Kotty666** [comment]
ist im ganz normalen bereich inzwischen also mit:

wget https://github.com/Kotty666/dbus-growatt-shinex/archive/refs/heads/main.zip
unzip main.zip "dbus-growatt-shinex-main/*" -d /data
mv /data/dbus-growatt-shinex-main /data/dbus-growatt-shinex
chmod a+x /data/dbus-growatt-shinex/install.sh
/data/dbus-growatt-shinex/install.sh
rm main.zip

**Comment by Sven4597** [comment]
> ist im ganz normalen Bereich. Seitdem also mit:
> 
> wget https://github.com/Kotty666/dbus-growatt-shinex/archive/refs/heads/main.zip entpacken Sie main.zip "dbus-growatt-shinex-main/*" -d /data mv /data/dbus-growatt-shinex-main /data/dbus-growatt-shinex chmod a+x /data/dbus-growatt-shinex/install.sh /data/dbus-growatt-shinex/install.sh rm main.zip

Kann du mir den Befehl für den uninstall schicken bekomme es nicht hin.
mit dem Befehl oben geht es nicht

**Comment by Sven4597** [comment]
Hallo,

habe es jetzt hin bekommen dass es läuft nur werden falsche Werte angezeigt.
Könntest du mal bitte nochmal schauen?

Wenn die Leistung höher ist passen die Werte nur abends bei niedrigen passt es nicht.
Hier noch ein Bild
![Victron4](https://github.com/Kotty666/dbus-growatt-shinex/assets/47686540/608314f9-46d8-47ac-a777-795a6c9e5db1)

Grüße Sven

**Comment by Kotty666** [comment]
@Sven4597 ,
ich habe mal versucht was anzupassen - hol dir mal die aktuelle dbus-growatt-shinex.py datei und schau ob es damit besser wird.

**Comment by Fahrzeug-cpu** [comment]
Hallo die neue Datei habe ich eingespielt. Die werte passen bei mir auch nicht 100%ig. Habe 2 Skripte laufen 1mal 3Phasig und 1 Phasig

**Comment by Fahrzeug-cpu** [comment]
![12ktl](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/938eba78-41f9-4fcf-aac5-30440ea2f31e)
![3000min](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/5541dd4b-4ec7-495d-99b3-179b9a84ecbe)

**Comment by Kotty666** [comment]
@Fahrzeug-cpu ja das mit den unterschieden sieht man auch in den JSON Datein vom Inverter. Die einzelnen Werte der Phasen zusammengerechnet sind immer weniger als die Output - allerdings habe ich noch keine wirklichen anhaltspunkt woher das kommt - meine vermutung ist dass bei den einzelnen Phasen der Wikrungsgrad von 1 angenommen wird dies aber nicht korrekt ist. Ist aber auch nur geraten. Es gibt aktuell 2 möglichkeitne aus meiner Sicht.

1. so lassen und damit Leben
2. den "Wirkungsgrad" berechnen und dann diesen wert auf die einzelnen Phasen anwenden so dass die einzelnen Phasen zum gesamt passen.

@Sven4597 @Fahrzeug-cpu welche Variante wäre euch lieber? Beides ist vermutlich nicht wirklich richtig

**Comment by Kotty666** [comment]
@Fahrzeug-cpu @Sven4597 ich habe mal die berechnung des Wirkungsgrades mit implementiert - testet mal ob es so nun besser ist.

**Comment by Fahrzeug-cpu** [comment]
> @Fahrzeug-cpu @Sven4597 ich habe mal die berechnung des Wirkungsgrades mit implementiert - testet mal ob es so nun besser ist.

Nun keine Verbindung mehr....
![keineverbindung](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/7eca0e42-8594-464a-bb98-ba516f242af7)

**Comment by Kotty666** [comment]
@Fahrzeug-cpu steht was im log bzw. is was zu sehen?

**Comment by Fahrzeug-cpu** [comment]
> @Fahrzeug-cpu steht was im log bzw. is was zu sehen?

Seid paar Version ist kein Logfile mehr vorhanden. ( Ist auch gut so, hatt mich immer den Speicher voll geschrieben).

**Comment by Kotty666** [comment]
@Fahrzeug-cpu doch die logs sind noch da nur werden die nun anders geschrieben und verwaltet. Die findest du unter /var/log/<name>/current.log

Ich habe aber gerade noch 2 Fehler gefunden und gefixt nun sollte es wieder laufen

**Comment by Fahrzeug-cpu** [comment]
> @Fahrzeug-cpu doch die logs sind noch da nur werden die nun anders geschrieben und verwaltet. Die findest du unter /var/log//current.log
> 
> Ich habe aber gerade noch 2 Fehler gefunden und gefixt nun sollte es wieder laufen

![Flasch](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/e891b7e8-35b9-4a02-80d8-b50605921655)

**Comment by Fahrzeug-cpu** [comment]
> @Fahrzeug-cpu doch die logs sind noch da nur werden die nun anders geschrieben und verwaltet. Die findest du unter /var/log//current.log
> 
> Ich habe aber gerade noch 2 Fehler gefunden und gefixt nun sollte es wieder laufen

Also ich habe mal geschaut, das Problem ist das VRM Portal/Venos den Wert AC Phase L1 nimmt für die Anzeige und die errechnung der Lasten etc...

Es müsste aber der Wert AC-gesamt da wo jetzt AC Phase L1 steht.

Bei dem 3Phassigen stimmt es auch nicht. 
![Uploading Flasch.PNG…]()

**Comment by Fahrzeug-cpu** [comment]
> @Fahrzeug-cpu doch die logs sind noch da nur werden die nun anders geschrieben und verwaltet. Die findest du unter /var/log//current.log
> 
> Ich habe aber gerade noch 2 Fehler gefunden und gefixt nun sollte es wieder laufen
Also ich habe mal geschaut, das Problem ist das VRM Portal/Venos den Wert AC Phase L1 nimmt für die Anzeige und die errechnung der Lasten etc...

Es müsste aber der Wert AC-gesamt da wo jetzt AC Phase L1 steht.

Bei dem 3Phassigen stimmt es auch nicht.
![Flasch](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/c6e92adc-1ed7-456f-9296-952ca370c275)

**Comment by Fahrzeug-cpu** [comment]
> @Fahrzeug-cpu doch die logs sind noch da nur werden die nun anders geschrieben und verwaltet. Die findest du unter /var/log//current.log
> 
> Ich habe aber gerade noch 2 Fehler gefunden und gefixt nun sollte es wieder laufen

Also ich habe mal geschaut, das Problem ist das VRM Portal/Venos den Wert AC Phase L1 nimmt für die Anzeige und die errechnung der Lasten etc...

Es müsste aber der Wert AC-gesamt da wo jetzt AC Phase L1 steht.

Bei dem 3Phassigen stimmt es auch nicht.

**Comment by Kotty666** [comment]
klick mal auf die PV-Wechselrichter kachel und zeige was er da anzeigt

**Comment by Fahrzeug-cpu** [comment]
> klick mal auf die PV-Wechselrichter kachel und zeige was er da anzeigt

![1phasigfalsch](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/041ec893-6c3f-4b7f-8c45-71e14a4d32dd)
![3phasig falsch](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/0a9c50b4-ab40-426f-969b-07ccee2475b1)

Das Problem was ich habe ist das er mir damit die AC Lasten falsch rechnet und ich somit alle Werte nicht Stimmen im Portal

**Comment by Kotty666** [comment]
auf die kachel in der seitenübersicht klicken bitte. 

Das sieht dann so aus:
![image](https://github.com/Kotty666/dbus-growatt-shinex/assets/10629883/fb969dc0-f38b-4e02-9053-caded8e2050f)

**Comment by Fahrzeug-cpu** [comment]
> auf die kachel in der seitenübersicht klicken bitte.
> 
> Das sieht dann so aus: ![image](https://private-user-images.githubusercontent.com/10629883/347365197-fb969dc0-f38b-4e02-9053-caded8e2050f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTExNDUsIm5iZiI6MTcyMDYxMDg0NSwicGF0aCI6Ii8xMDYyOTg4My8zNDczNjUxOTctZmI5NjlkYzAtZjM4Yi00ZTAyLTkwNTMtY2FkZWQ4ZTIwNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDExMjcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMmM5YjYyYTg1Y2M2NDc1OGRhMzUzYzkzNjBmODBiMzIxN2U0MTEwYWQ5YTg5OWZhNzI2YzFiNzI5NTJiYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L7xRN65Gd9ZQU74xocrS_thOgY8jwxQIbAWzkPSXv-8)

Das bekomme ich nicht hin. Habe alles ausprobiert. Aber bei Schwachlicht zeigt er nun 0 ob wohl er laut otti Übersicht noch 138Watt liefert. 
![Test3](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/3c5efd72-a21d-4725-bce6-a26afc6d56e8)

**Comment by Kotty666** [comment]
also das was da steht ergibt so alles keinen sinn.
Kannst du mal bitte wenn du den zustand hast des Json vom Stick posten?

**Comment by Fahrzeug-cpu** [comment]
> also das was da steht ergibt so alles keinen sinn. Kannst du mal bitte wenn du den zustand hast des Json vom Stick posten?

![Logjason](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/f00094d0-ce79-4179-92cc-94f34051f8d6)

**Comment by Kotty666** [comment]
hast du es auch als text? Alles abtippen ist irgendwie nicht so cool ;)

**Comment by Kotty666** [comment]
So ich habe gestern noch einen fehler gefunden - schau mal ob es nun passt

**Comment by Fahrzeug-cpu** [comment]
> So ich habe gestern noch einen fehler gefunden - schau mal ob es nun passt

Hey super jetzt passt es exakt. Werde heute Abend noch das Schwachlichtverhalten testen und berichten. Anbei Bilder des 1 und 3 Phasigen WR.
![Anzeige passt exakt](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/aa941ebe-709b-46f1-a5b7-ee99aeffab57)
![Anzeigepasst 3 phasen](https://github.com/Kotty666/dbus-growatt-shinex/assets/175016800/a12c2afc-9655-4965-8127-4ef972924236)

**Comment by Kotty666** [comment]
Lustig also meldet des ding an der Phase die Leistung inkl. Blindleistung und gesamt ist dann abzüglich der Blindleistung

**Comment by Sven4597** [comment]
bei mir wird leider nix mehr angezeigt. An was kann das liegen?

![image](https://github.com/Kotty666/dbus-growatt-shinex/assets/47686540/6d0a15cd-02de-405e-8295-581991aa329c)

**Comment by Kotty666** [comment]
kannst du mal ins log schauen was da drinnen steht? Wenn da nichts drinnen steht könntest du mal eines der python Scripte händisch starten und schauen was da raus kommt

**Comment by Fahrzeug-cpu** [comment]
> kannst du mal ins log schauen was da drinnen steht? Wenn da nichts drinnen steht könntest du mal eines der python Scripte händisch starten und schauen was da raus kommt

Also das schwachlicht Verhalten ist super die Werten stimmen 1:1 :-) 

nur was ich auch seid 2 Tagen feststelle das morgens einfach 0w angezeigt wird obwohl die Sonne schon da ist 08:31. starte ich das Venus os neu ist alles da und funktioniert.

**Comment by Sven4597** [comment]
Bei mir gehen die Wechselrichter nach dem einrichten und am nächsten Tag nur noch einer von den drei.
![Screenshot_20240713_084553_VRM](https://github.com/user-attachments/assets/e0dd0a1a-8e3d-401c-aed2-8e67f8380e10)

**Comment by Fahrzeug-cpu** [comment]
> Bei mir gehen die Wechselrichter nach dem einrichten und am nächsten Tag nur noch einer von den drei. ![Screenshot_20240713_084553_VRM](https://private-user-images.githubusercontent.com/47686540/348454979-e0dd0a1a-8e3d-401c-aed2-8e67f8380e10.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzkwNjAsIm5iZiI6MTcyMDkzODc2MCwicGF0aCI6Ii80NzY4NjU0MC8zNDg0NTQ5NzktZTBkZDBhMWEtOGUzZC00MDFjLWFlZDItOGU2N2Y4MzgwZTEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA2MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNjZkZDA0YzViNGZjNWFkZDNhYjA0ZjYwN2JlMzA1Zjk0MWRiYjE5ODcxM2QxNzQ3YjY1YmEyN2JlZWQ3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bHGtjrS0ojb52jDv3rASVQsqcYSBvoPEJstCheRExqM)

Habe heute morgen das selbe Verhalten feststellen können. Einer der der beiden WR wurde nicht angezeigt. Nach einem Neustart des Multiplus/ Venos OS laufen beide. 

Vieleicht muss hier noch etwas im Skript angepasst werden ?

**Comment by Kotty666** [comment]
hm schwer für mich da zu debuggen. Ich müsste wissen ob des script dann in der früh wenn der zustand besteht etwas spezielles ins log schreibt oder man was anderes sieht.
Da ich seit über einem Jahr keinen Growatt mehr habe kann ich es selbst nicht testen

**Comment by Fahrzeug-cpu** [comment]
> hm schwer für mich da zu debuggen. Ich müsste wissen ob des script dann in der früh wenn der zustand besteht etwas spezielles ins log schreibt oder man was anderes sieht. Da ich seit über einem Jahr keinen Growatt mehr habe kann ich es selbst nicht testen

Das LOG ist leer nach dem Neustart des Victrons. *** CCGX booted (0) ***

**Comment by Kotty666** [comment]
nach dem neustart ist ein schlechter zeitpunkt - wenn dann müsste man drauf schauen wenn das script gerade nicht mehr richtig läuft

**Comment by Sven4597** [comment]
Wie kann ich den log auslesen?

**Comment by Fahrzeug-cpu** [comment]
Die findest du unter /var/log//current.log

**Comment by Fahrzeug-cpu** [comment]
> Wie kann ich den log auslesen?
Die findest du unter /var/log//current.log

**Comment by Fahrzeug-cpu** [comment]
> nach dem neustart ist ein schlechter zeitpunkt - wenn dann müsste man drauf schauen wenn das script gerade nicht mehr richtig läuft

Das sollte ein Log sein wo es nicht läuft morgens: (IP habe ich die letzen 3 geXXX


@400000006692183239a64b0c HTTPConnectionPool(host='192.168.178.XXX', port=80): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5a2a628>: Failed to establish a new connection: [Errno 113] No route to host'))
@400000006692183239a6f6ec HTTPConnectionPool(host='192.168.178.XXX', port=80): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5ab45c8>: Failed to establish a new connection: [Errno 113] No route to host'))
@400000006692183239a754ac HTTPConnectionPool(host='192.168.178.XXX', port=80): Read timed out.
@400000006692183239af20c4 HTTPConnectionPool(host='192.168.178.XXX', port=80): Read timed out.
@4000000066921bd629b204d4 *** CCGX booted (0) ***

**Comment by Fahrzeug-cpu** [comment]
> Bei mir gehen die Wechselrichter nach dem einrichten und am nächsten Tag nur noch einer von den drei. ![Screenshot_20240713_084553_VRM](https://private-user-images.githubusercontent.com/47686540/348454979-e0dd0a1a-8e3d-401c-aed2-8e67f8380e10.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjQ5ODMsIm5iZiI6MTcyMTA2NDY4MywicGF0aCI6Ii80NzY4NjU0MC8zNDg0NTQ5NzktZTBkZDBhMWEtOGUzZC00MDFjLWFlZDItOGU2N2Y4MzgwZTEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE3MzEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNGMyZjgzZThiMDk0YmM0ZGVjMzc5ZGUyMjYyZDc5MmYxYTllMDlmYjhjMWNhODU0N2RhOTAyNDFhN2YyZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2v2Z7ZoacGX-WPig5vpRLQx9AHnOk84RaPvYcAIVwFw)

Ich denke das liegt an der 2ten Instantz die wir installiert haben. Vieleicht muss hier etwas gefixt werden ?

**Comment by d0m1n1qu3** [comment]
also ich habe jetzt nicht alles im detail gelesen.
aber ich habe 4 growatt mit dem plugin hier am laufen.

einfach das ganze mehrfach installieren.
wichtig war glaub ich aber unterschiedliche Deviceinstance in der config.ini

**Comment by Fahrzeug-cpu** [comment]
> also ich habe jetzt nicht alles im detail gelesen. aber ich habe 4 growatt mit dem plugin hier am laufen.
> 
> einfach das ganze mehrfach installieren. wichtig war glaub ich aber unterschiedliche Deviceinstance in der config.ini

Das Problem ist das morgen nach Sonnenaufgang nicht alle Skripte "anlaufen". Wir haben ja auch mehere. 
Device Instance ist klar bei mir hat WR 1 die 41 und WR 2 die 42.

Teste mal die aktule Pyton datei und berichte uns wie es bei dir läuft. ( Sichere aber zuvor die alte)

**Comment by Fahrzeug-cpu** [comment]
Also ich habe heute morgen das Verhalten mir angeschaut das 2te Skript läuft nicht "an". Habe diverse Screenshot erstellt und die Log Files gesichert vor dem Neustart der Venos OS. 
![Installverzeichniss](https://github.com/user-attachments/assets/da4b9114-48e7-4bab-a818-9406040f6563)


![Console](https://github.com/user-attachments/assets/ba588832-3639-4831-94fe-c906cbadcdc7)

[Logs.zip](https://github.com/user-attachments/files/16244266/Logs.zip)

**Comment by Kotty666** [comment]
hm daraus erkennt man leider nichts :(
Gäbe es die möglichkeit direkt auf das gerät per ssh mal drauf zu schauen? Über Teamviewer oder so?

**Comment by Kotty666** [comment]
> > hm daraus erkennt man leider nichts :( Gäbe es die möglichkeit direkt auf das gerät per ssh mal drauf zu schauen? Über Teamviewer oder so? Also in der früh wenn es nicht richtig geht.
> 
> Ja logo geht das. Musst mir nur sagen wie. Könnten wir uns evtl. per Email absprechen oder PN (wenn das hier gibt ?)

Wir können uns gerne mal pe email absprechen (kotty - at - guns-n-girls.de) oder alternativ bin ich auch im Discord unter kotty666 unterwegs.

**Comment by Sven4597** [comment]
Gibt es schon Neuigkeiten?

Grüße Sven

**Comment by Kotty666** [comment]
Hi @Sven4597 ,

also scheinbar ist der neue loggingmeachnismus schuld - dieser hat Probleme wenn 2 Scripte das Gleiche Logfile benutzen. Ich habe nun das installscript angepasst damit dies nicht mehr passiert. Alternativ kannst du bei deinen installationen in dieser Datei:
https://github.com/Kotty666/dbus-growatt-shinex/blob/main/service/log/run

das 
`exec multilog t s153600 n2 /var/log/dbus-growatt-shinex `
anpassen so dass jede Installation des scriptes ein eigenes Logfile erhält damit sollte das Problem beheben. 

Im angepassten Installationsmechanismus wird der Logpfad erst bei der Installation definiert und reingeschrieben damit sollte das Problem bei neuen installationen nicht mehr der fall sein.

**Comment by Sven4597** [comment]
Super vielen vielen dank dir für deine Mühe jetzt geht es.
