### ISSUE TITLE
When Inverter Start Up Total Generated Power is stored as Data Point into VenusOS Graphs

### ISSUE THREAD

**Issue by v1rus317** [Kotty666/dbus-growatt-shinex#7]
Hello,

I am using the script with a Growatt MOD 5000TL3-X and I am facing one problem:
In the morning when my Growatt Inverter starts up the total amount of generated power in kWh (TotalGenerateEnergy) gets added to the actual point in time as solar generated power and also for consumption. 
So for example at the time 06:36 in the morning i have now solar power 25,4kWh and also consumption 25,4kWh which ruins the scaling of my graph for the whole day.

If i look at the graph data of the posted Energy during the night, i can see that all energies (TotalGenerateEnergy) related values go down to 0.0kWh at night.
In the morning at first the total energy is shown only on L1.
Then in the next data point the Energy is divided by three into the three phases.

If i compare that to other third-party inverters that are added via Dbus-Interface (Like Dbus OpenDTU for Hoymiles), there the total amount of energy is posted always also during the night.

That the total energy is going to 0kWh is a problem with the custom firmware on the ShineX-WiFi Stick, but i think that the fact that the energy is at first in the morning only shown on L1 and not divided by three to display on all phases, looks like maybe a issue with this git?

Thanks in advance!

**Comment by v1rus317** [comment]
https://github.com/Kotty666/dbus-growatt-shinex/blob/fb467651fa441e8aed6aa6fd7ff4ff323a3909cc/dbus-growatt-shinex.py#L252-L269

I found out, that if the initial values for this data is set to value 0, then for each of this data a zero value is saved in the graph in VRM portal.

I found out that if these initial values are replaced by `None` then no values are stored into the graphs.
This solves part of the issue described above.

```
'/ErrorCode': {'initial': None, 'textformat': '' }, 
 '/Ac/Energy/Forward': {'initial': None, 'textformat': _kwh}, 
 '/Ac/Power': {'initial': None, 'textformat': _w}, 
  
 '/Ac/L1/Current': {'initial': None, 'textformat': _a}, 
 '/Ac/L1/Power': {'initial': None, 'textformat': _w}, 
 '/Ac/L1/Voltage': {'initial': None, 'textformat': _v}, 
 '/Ac/L1/Energy/Forward': {'initial': None, 'textformat': _kwh}, 
  
 '/Ac/L2/Current': {'initial': None, 'textformat': _a}, 
 '/Ac/L2/Power': {'initial': None, 'textformat': _w}, 
 '/Ac/L2/Voltage': {'initial': None, 'textformat': _v}, 
 '/Ac/L2/Energy/Forward': {'initial': None, 'textformat': _kwh}, 
  
 '/Ac/L3/Current': {'initial': None, 'textformat': _a}, 
 '/Ac/L3/Power': {'initial': None, 'textformat': _w}, 
 '/Ac/L3/Voltage': {'initial': None, 'textformat': _v}, 
 '/Ac/L3/Energy/Forward': {'initial': None, 'textformat': _kwh},
```


Second part of my issue is, that during the startup of the inverter, when the ShineX Wifi stick is already powered on but the inverter is still booting, it will send zeros for all values in the JSON-String.
That zero values will be stored in the Graphs.
To avoid this, it is possible to check that the object TotalGenerateEnergy is greater than 0 and only then store it to the Dbus.

So for example:

```
if meter_data['TotalGenerateEnergy'] > 0:
   self._dbusservice['/Ac/Energy/Forward'] = meter_data['TotalGenerateEnergy']
```

At least this solved the problem for me. I also made this check where the Energy is written to each individual phase.

**Comment by Kotty666** [comment]
@v1rus317 
thanks for that, i've changed the stuff and merged with https://github.com/Kotty666/dbus-growatt-shinex/pull/10
