### ISSUE TITLE
Bug fix: % Operator is missing in _signOfLife

### ISSUE THREAD

**Issue by v1rus317** [Kotty666/dbus-growatt-shinex#8]
Hello,

i found that the % operator is missing for the string format code line:

https://github.com/Kotty666/dbus-growatt-shinex/blob/fb467651fa441e8aed6aa6fd7ff4ff323a3909cc/dbus-growatt-shinex.py#L155

It should look like this:

`logging.info("Last '/Ac/Energy/Forward': %s" % (self._dbusservice['/Ac/Energy/Forward'])) `

**Comment by Kotty666** [comment]
Thx for that. I'vd fixed it with https://github.com/Kotty666/dbus-growatt-shinex/pull/9
